apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-tasky-app
  namespace: tasky-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tasky
  template:
    metadata:
      labels:
        app: tasky
    spec:
      serviceAccountName: tasky-app-sa
      containers:
      - name: tasky-container
        image: 772935232126.dkr.ecr.eu-west-1.amazonaws.com/tasky:latest
        ports:
        - containerPort: 8080
