name: Build and Publish a Docker image to ECR

on:
  push:
    branches: ['main']

env:
  AWS_REGION: eu-west-1
  ECR_REGISTRY: 772935232126.dkr.ecr.eu-west-1.amazonaws.com
  IMAGE_NAME: tasky

# Permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC_ECR
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }} .
          docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.ECR_REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Push Docker image to Amazon ECR
        run: |
          docker push ${{ env.ECR_REGISTRY }}/${{ env.IMAGE_NAME }}:latest